### ISSUE TITLE
Please choose a license

### ISSUE THREAD

**Issue by aleksandar-todorovic** [kmaasrud/awesome-obsidian#11]
Hey,

Thank you for the repo. Please choose a license so that you'll allow others the freedom to do more with your list. See [this link](https://choosealicense.com/no-permission/) for what happens when you don't choose one. Long story short: everything remains fully copyrighted by you, and others don't get the permission to copy or make modifications.

I recommend going through [Creative Commons' license picker](https://creativecommons.org/choose/) to choose an appropriate one, or going with [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) which effectively makes your work available to everyone without any restrictions.

**Comment by kmaasrud** [comment]
Thanks for the heads up, you're absolutely correct! CC0 license is now added
