### ISSUE TITLE
Add gifs of CSS tweaks

### ISSUE THREAD

**Issue by Raduan77** [kmaasrud/awesome-obsidian#23]
I think it would be great to add gifs of how the CSS tweaks would work to the readme. Otherwise, it's hard to decide whether to use it or not.

**Comment by kmaasrud** [comment]
I agree, that would be a nice addition!

Sadly, I am not actively maintaining this repo, only handling incoming PRs. If you or someone else would like to give it a go, please feel free to submit a PR referencing this issue and I will most likely merge it :smile:

**Comment by konhi** [comment]
Done!
