### ISSUE TITLE
CSS Tweaks section is outdated

### ISSUE THREAD

**Issue by konhi** [kmaasrud/awesome-obsidian#27]
1. CSS Tweaks are now called snippets
2. There's no `obsidian.css` anymore. Instead user may create CSS files in `vault/.obsidian/snippets/`
    - I suggest adding download button for every snippet

**Comment by konhi** [comment]
Also, there's a separate [repository for many CSS Snippets.](https://github.com/Dmitriy-Shulha/obsidian-css-snippets) Wouldn't it be a better option to link mentioned repo?

**Comment by kmaasrud** [comment]
Thanks for the suggestion! As you can see, I left some thoughts on this in the issue above ^

**Comment by kmaasrud** [comment]
Closing in favor of #29
