### ISSUE TITLE
Updated look for CSS snippets

### ISSUE THREAD

**Issue by kmaasrud** [kmaasrud/awesome-obsidian#29]
@kohni, you can create a PR that redoes the current CSS snippets, using the style you proposed: A title for the snippet, a link to a file containing the snippet (inside a `css` directory or something) and a picture/GIF (#23) showing the snippet in action - perhaps even with a before/after where necessary.

You can redo as many/few as you feel like in the beginning. The imporant thing is that we get an updated look for showcasing the snippets, then we can pull in all the new ones.

**Comment by konhi** [comment]
Done! 😊

**Comment by kmaasrud** [comment]
Forgot to close this, thanks for the reminder
