### ISSUE TITLE
Where can I get the Obsidian.css ?

### ISSUE THREAD

**Issue by Erik262** [kmaasrud/awesome-obsidian#3]
Hi folks,

I only want to put some little tweaks for Obsidian. But I can't find the original Obsidian.css file to start with.

**Comment by b3u** [comment]
There isn't really one, as far as I know. But you can peek at the HTML and CSS by opening the devtools (<kbd>ctrl+shift+i</kbd>)

Also, there's a nice post about it [here](https://forum.obsidian.md/t/getting-comfortable-with-obsidian-css/133/18)
